export const WORK_PREFERENCES = ["Remote", "Hybrid", "On-site"] as const;

export const SALARY_TYPES = ["Hourly", "Daily", "Weekly", "Monthly", "Annually"] as const;

export const JOB_TYPES = ["Permanent", "Contractual", "Freelance", "Part Time", "Internship"] as const;

export const GENDER_OPTIONS = ["All", "Male", "Female", "Preferred not to say", "None"] as const;

export const CURRENCIES = [
  "USD",
  "EUR",
  "GBP",
  "PKR",
  "AED",
  "SAR",
  "INR",
  "CAD",
  "AUD",
  "SGD",
  "MYR",
  "BHD",
  "QAR",
  "KWD",
  "OMR",
  "CNY",
  "JPY",
  "CHF",
  "SEK",
  "NOK",
  "DKK",
  "ZAR",
  "NGN",
  "EGP",
  "BRL",
  "MXN"
] as const;

export const EDUCATION_DEGREES = [
  "High School Diploma",
  "Associate Degree",
  "Bachelor of Arts (BA)",
  "Bachelor of Science (BSc)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Engineering (BEng)",
  "Bachelor of Computer Science (BCS)",
  "Bachelor of Commerce (BCom)",
  "Master of Arts (MA)",
  "Master of Science (MSc)",
  "Master of Business Administration (MBA)",
  "Master of Engineering (MEng)",
  "Master of Computer Science (MCS)",
  "Master of Public Health (MPH)",
  "Doctor of Philosophy (PhD)",
  "Doctor of Medicine (MD)",
  "Juris Doctor (JD)",
  "Chartered Accountant (CA)",
  "ACCA",
  "CPA",
  "CFA",
  "Diploma",
  "Professional Certificate",
  "No formal education required"
] as const;

export const BENEFIT_OPTIONS = [
  "Health insurance",
  "Dental insurance",
  "Vision insurance",
  "Life insurance",
  "Disability insurance",
  "Retirement plan / 401(k)",
  "Pension plan",
  "Stock options",
  "Performance bonus",
  "Annual bonus",
  "Paid time off",
  "Sick leave",
  "Parental leave",
  "Remote work allowance",
  "Flexible hours",
  "Hybrid work",
  "Learning & development budget",
  "Gym membership",
  "Wellness program",
  "Transport allowance",
  "Meal allowance",
  "Relocation assistance",
  "Visa sponsorship",
  "Childcare support",
  "Company laptop",
  "Phone allowance",
  "Internet allowance"
] as const;

export const SKILL_SUGGESTIONS = [
  "Communication",
  "Leadership",
  "Project management",
  "Problem solving",
  "Teamwork",
  "Time management",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Python",
  "Java",
  "SQL",
  "PostgreSQL",
  "MongoDB",
  "AWS",
  "Azure",
  "Docker",
  "Kubernetes",
  "Git",
  "CI/CD",
  "Agile",
  "Scrum",
  "Sales",
  "Marketing",
  "Customer service",
  "Data analysis",
  "Excel",
  "Power BI",
  "Tableau",
  "Accounting",
  "Finance",
  "HR management",
  "Recruitment",
  "Negotiation",
  "Public speaking",
  "Content writing",
  "SEO",
  "Graphic design",
  "UI/UX design",
  "Figma",
  "Quality assurance",
  "Manual testing",
  "Automation testing"
] as const;
